version: '3.7'

services:
  blog_pet:
    container_name: blog_pet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    tty: true
    networks:
      - webnet
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - webnet

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - webnet
    depends_on:
        - redis

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - webnet
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - webnet

networks:
  webnet:
volumes:
  postgres:
  pgadmin:
